"""Runs every Phase 0 correction regression and writes reproducible outputs to ../../evidence/regress/.
Usage: python3 run_regressions.py            (Python 3.11 stdlib only; ~20 s)
Exit code 0 only if every regression reports all checks PASS. NOT PRODUCTION CODE."""
import hashlib
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "evidence", "regress"))
REGRESSIONS = [
    ("regress_audit_repro.py", "P0-02 / P0-03 (auditor's script, byte-identical)"),
    ("regress_p0_02_txn_recovery.py", "P0-02"),
    ("regress_p0_03_save_lineage.py", "P0-03"),
    ("regress_p0_04_gate.py", "P0-04"),
    ("regress_p1_01_02_identity.py", "P1-01 / P1-02"),
    ("regress_p1_03_time.py", "P1-03"),
    ("regress_p1_04_sysjournal.py", "P1-04"),
    ("regress_p1_05_npc_identity.py", "P1-05"),
    ("regress_p1_06_legacy.py", "P1-06"),
    ("regress_p2_01_backup.py", "P2-01"),
]
SUMMARY_RE = re.compile(r"^(.+): (\d+)/(\d+) PASS$", re.M)


def sha(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()


def main():
    os.makedirs(OUT, exist_ok=True)
    rows, ok_all, t_all = [], True, time.time()
    for script, finding in REGRESSIONS:
        t0 = time.time()
        r = subprocess.run([sys.executable, script], cwd=HERE, capture_output=True, text=True)
        dt = time.time() - t0
        text = r.stdout + (("\nSTDERR:\n" + r.stderr) if r.stderr else "")
        m = SUMMARY_RE.findall(r.stdout)
        passed, total = (int(m[-1][1]), int(m[-1][2])) if m else (0, 0)
        ok = r.returncode == 0 and total > 0 and passed == total
        ok_all &= ok
        with open(os.path.join(OUT, script.replace(".py", ".out.md")), "w", encoding="utf-8") as fh:
            fh.write(f"<!-- generated by phase0-probes/regress/run_regressions.py from {script}; exit={r.returncode} -->\n\n```\n{text}```\n")
        rows.append(f"| `{script}` | {finding} | {passed}/{total} | {'PASS' if ok else 'FAIL'} | `{sha(os.path.join(HERE, script))}` |")
        print(f"{'PASS' if ok else 'FAIL'}  {script:34s} {passed:5d}/{total:<5d} {dt:6.1f} s")
    total_time = time.time() - t_all
    with open(os.path.join(OUT, "SUMMARY.md"), "w", encoding="utf-8") as fh:
        fh.write("| Regression | Finding | Checks passed | Result | Source SHA-256 |\n|---|---|---:|---|---|\n")
        fh.write("\n".join(rows) + "\n")
        fh.write(f"\nAll regressions: {'PASS' if ok_all else 'FAIL'}\n")
    print(f"regressions total run time: {total_time:.1f} s")
    print("RESULT:", "PASS" if ok_all else "FAIL")
    return 0 if ok_all else 1


if __name__ == "__main__":
    sys.exit(main())
