"""Runs every Phase 0 reference simulation and writes reproducible outputs to ../../evidence/sim/.
Usage: python3 run_all.py        (Python 3.11 stdlib only; ~3 minutes)
Exit code 0 only if every simulation reports RESULT: PASS. NOT PRODUCTION CODE."""
import hashlib
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "evidence", "sim"))
SIMS = ["lsax_ref_math.py", "valuation_ref.py", "npcgen_ref.py", "heat_ref.py", "journal_timeline_ref.py"]


def main():
    os.makedirs(OUT, exist_ok=True)
    ok = True
    summary = []
    for sim in SIMS:
        r = subprocess.run([sys.executable, sim], cwd=HERE, capture_output=True, text=True)
        text = r.stdout + (("\nSTDERR:\n" + r.stderr) if r.stderr else "")
        path = os.path.join(OUT, sim.replace(".py", ".out.md"))
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(f"<!-- generated by phase0-probes/sim/run_all.py from {sim}; exit={r.returncode} -->\n\n{text}")
        passed = r.returncode == 0 and ("RESULT: PASS" in text or "self-check OK" in text)
        ok &= passed
        src_hash = hashlib.sha256(open(os.path.join(HERE, sim), "rb").read()).hexdigest()
        summary.append(f"| `{sim}` | {'PASS' if passed else 'FAIL'} | `{src_hash}` |")
    with open(os.path.join(OUT, "SUMMARY.md"), "w", encoding="utf-8") as fh:
        fh.write("| Simulation | Result | Source SHA-256 |\n|---|---|---|\n" + "\n".join(summary) + "\n")
    print("\n".join(summary))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
