"""Runs every Phase 0 reference simulation and every correction regression; writes reproducible outputs to
../../evidence/sim/ and ../../evidence/regress/ (Python 3.11 stdlib only). NOT PRODUCTION CODE.

Usage:
  python3 run_all.py            fast mode (default): journal model 60 episodes per (mix, granularity) — ~2 min total
  python3 run_all.py --audit    audit-grade: journal model 200 episodes per (mix, granularity) — ~4 min total
Exit code 0 only if every simulation reports RESULT: PASS and every regression passes all checks."""
import argparse
import hashlib
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "evidence", "sim"))
REGRESS = os.path.normpath(os.path.join(HERE, "..", "regress"))
SIMS = ["lsax_ref_math.py", "valuation_ref.py", "npcgen_ref.py", "heat_ref.py", "identity_ref.py", "time_ref.py",
        "sysjournal_ref.py", "legacy_ref.py", "journal_timeline_ref.py"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--audit", action="store_true", help="audit-grade journal run (200 episodes per mix x granularity)")
    args = ap.parse_args()
    episodes = 200 if args.audit else 60
    os.makedirs(OUT, exist_ok=True)
    ok, summary, t_all = True, [], time.time()
    for sim in SIMS:
        cmd = [sys.executable, sim] + (["--episodes", str(episodes)] if sim == "journal_timeline_ref.py" else [])
        t0 = time.time()
        r = subprocess.run(cmd, cwd=HERE, capture_output=True, text=True)
        dt = time.time() - t0
        text = r.stdout + (("\nSTDERR:\n" + r.stderr) if r.stderr else "")
        with open(os.path.join(OUT, sim.replace(".py", ".out.md")), "w", encoding="utf-8") as fh:
            fh.write(f"<!-- generated by phase0-probes/sim/run_all.py from {' '.join(cmd[1:])}; exit={r.returncode} -->\n\n{text}")
        passed = r.returncode == 0 and ("RESULT: PASS" in text or "self-check OK" in text)
        ok &= passed
        src_hash = hashlib.sha256(open(os.path.join(HERE, sim), "rb").read()).hexdigest()
        summary.append(f"| `{' '.join(cmd[1:])}` | {'PASS' if passed else 'FAIL'} | {dt:.1f} s | `{src_hash}` |")
        print(f"{'PASS' if passed else 'FAIL'}  {' '.join(cmd[1:]):42s} {dt:6.1f} s")
    r = subprocess.run([sys.executable, "run_regressions.py"], cwd=REGRESS, capture_output=True, text=True)
    print(r.stdout.rstrip())
    reg_ok = r.returncode == 0 and "RESULT: PASS" in r.stdout
    ok &= reg_ok
    total = time.time() - t_all
    with open(os.path.join(OUT, "SUMMARY.md"), "w", encoding="utf-8") as fh:
        fh.write(f"Mode: {'audit-grade (200 episodes)' if args.audit else 'fast (60 episodes)'}; total run time {total:.1f} s "
                 f"(simulations + regressions, one CPU, Python {sys.version.split()[0]}).\n\n")
        fh.write("| Simulation | Result | Run time | Source SHA-256 |\n|---|---|---:|---|\n" + "\n".join(summary) + "\n")
        fh.write(f"\nCorrection regressions (`phase0-probes/regress/run_regressions.py`, details in `evidence/regress/`): "
                 f"{'PASS' if reg_ok else 'FAIL'}\n")
    print(f"TOTAL run time: {total:.1f} s")
    print("RESULT:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
